Finish add new plan and assign activity features. Modify plan and today UI to remove bugs.
TODO: add new activity feature, settings menu and cloud database.

bug report:
bug: assign many activities in a short time, especially when assign the same activity (stress test)
outcome: got kick back to main UI (plans fragment), do the same thing another 2 times will lead to app crash.
error: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x48 in tid 9006.
solution: ignore for now.

bug: pre-created plan in other plans category doesn't have day list in plan fragment.
solution: will solve tomorrow.